Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMedia.Models;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace SocialMedia.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        SocialMediaDBEntities db = new SocialMediaDBEntities();

        //Check Current User is the Author of a Blog
        public bool CheckUserAuthor(tb_Blog b) {
            if (!User.Identity.IsAuthenticated) {
                return false;
            }
            var CurrentUserId = User.Identity.GetUserId();
            var user = db.tb_UserInfo.Where(u => u.UserId == CurrentUserId).FirstOrDefault();
            if (user.Id != b.Author)
            {
                return false;
            }
            return true;
        }


        public ActionResult Index()
        {
            List<Blog> lstBlog = new List<Blog>();
            
            foreach (var item in db.tb_Blog.ToList()) {
                Blog b = new Blog(item);
                lstBlog.Add(b);
            }
            return View(lstBlog);
        }

        [Authorize]
        public ActionResult Create(int? groupId, string returnUrl) {
            var UserId = User.Identity.GetUserId();
            ViewBag.UserId = UserId;

            if (groupId != null) {
                Session["GroupId"] = groupId;
            }
            if (!String.IsNullOrEmpty(returnUrl)) {
                Session["returnUrl"] = returnUrl;
            }

            return View();
        }

        
        [HttpPost]
        [Authorize]
        public ActionResult Create(Blog blog)
        {
            if (!ModelState.IsValid) {
                return View(blog);
            }
            tb_Blog b = new tb_Blog();
            var UserId = User.Identity.GetUserId();
            b.Author = db.tb_UserInfo.Where(u => u.UserId == UserId).FirstOrDefault().Id;
            b.Title = blog.Title;
            b.Content = blog.Content;
            tb_Blog addedBlog = DAL.DBContext.addNewBlog(b);

            if (Session["GroupId"] != null) {
                tb_BlogGroup blogGroup = new tb_BlogGroup();
                blogGroup.BlogId = addedBlog.Id;
                blogGroup.GroupId = Convert.ToInt32(Session["GroupId"]);
                db.tb_BlogGroup.Add(blogGroup);
                db.SaveChanges();

                Session["GroupId"] = null;
            }

            if (Session["returnUrl"] != null) {
                var url = Session["returnUrl"].ToString();
                Session["returnUrl"] = null;
                return Redirect(url);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int? id) {
            if (id == null) {
                return RedirectToAction("Index");
            }
            
            tb_Blog b = db.tb_Blog.Where(bl => bl.Id == id).FirstOrDefault();
            if (!CheckUserAuthor(b)) {
                return RedirectToAction("Index");
            }
            Blog blog = new Blog(b);
            return View(blog);
        }

        [HttpPost]
        public ActionResult Edit(Blog blog) {
            if (!ModelState.IsValid) {
                return View(blog);
            }
            Blog.EditBlogDB(blog);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int? id, string returnUrl) {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            tb_Blog b = db.tb_Blog.Where(bl => bl.Id == id).FirstOrDefault();
            if (!CheckUserAuthor(b))
            {
                return RedirectToAction("Index");
            }
            Blog blog = new Blog(b);
            return View(blog);
        }

        [HttpPost]
        public ActionResult Delete(int id, string returnUrl) {
            
            DAL.DBContext.deleteBlog(id);
            if (!String.IsNullOrEmpty(returnUrl)) {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int id, string comment, int? pageNumber) {
            //Add a comment to a Blog with Current User
            if (!String.IsNullOrEmpty(comment) && User.Identity.IsAuthenticated)
            {
                tb_Comment cmt = new tb_Comment();
                cmt.BlogId = id;
                var currentUserId = User.Identity.GetUserId();
                cmt.UserId = db.tb_UserInfo.Where(u => u.UserId == currentUserId).FirstOrDefault().Id;
                cmt.Content = comment;
                db.tb_Comment.Add(cmt);
                db.SaveChanges();
            }
            if (pageNumber == null) {
                pageNumber = 1;
            }
            int itemsPerPage = 3;
            tb_Blog bl = db.tb_Blog.Where(b => b.Id == id).FirstOrDefault();
            Blog blog = new Blog(bl);

            List<tb_Comment> lstComment = db.tb_Comment.Where(c => c.BlogId == id).ToList();
            lstComment.Reverse();
            int pageCount = lstComment.Count() / itemsPerPage;
            if (lstComment.Count() % itemsPerPage != 0) {
                pageCount += 1;
            }

            lstComment = lstComment.Skip(Convert.ToInt32(pageNumber - 1) * itemsPerPage).Take(itemsPerPage).ToList();

            if (checkUserLikeBlog(id))
            {
                ViewBag.IsLike = "Like";
            }

            ViewBag.PageCount = pageCount;
            ViewBag.CurrentPage = pageNumber;
            ViewData["Comments"] = lstComment;
            return View(blog);
        }

        //Check Current User Like a blog: take Blog's Id to return user like or not
        public bool checkUserLikeBlog(int BlogId) {
            if (!User.Identity.IsAuthenticated) {
                return false;
            }
            var currentUserId = User.Identity.GetUserId();
            var userInfoId = db.tb_UserInfo.Where(u => u.UserId == currentUserId).FirstOrDefault().Id;
            var obj = db.tb_Favorite.Where(o => o.BlogId == BlogId && o.UserId == userInfoId).FirstOrDefault();
            if (obj != null) {
                return true;
            }
            return false;
        }

        [Authorize]
        public ActionResult Like(int id, string returnUrl) {
            tb_Favorite favor = new tb_Favorite();
            favor.BlogId = id;
            var user = DAL.DBContext.GetUserInfo(User.Identity.GetUserId());
            favor.UserId = user.Id;
            db.tb_Favorite.Add(favor);
            db.SaveChanges();
            if (!String.IsNullOrEmpty(returnUrl)) {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Detail", new { id = id });
        }

        [Authorize]
        public ActionResult Unlike(int id, string returnUrl) {
            var userId = DAL.DBContext.GetUserInfo(User.Identity.GetUserId()).Id;
            tb_Favorite favor = db.tb_Favorite.Where(f => f.BlogId == id && f.UserId == userId).FirstOrDefault();
            db.tb_Favorite.Remove(favor);
            db.SaveChanges();
            if (!String.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Detail", new { id = id });
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SocialMedia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialMedia.Controllers
{
    //[Authorize]
    public class UsersController : Controller
    {
        public SocialMediaDBEntities db = new SocialMediaDBEntities();
        public ApplicationDbContext context = new ApplicationDbContext();
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        // GET: Users
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                ViewBag.displayMenu = "No";

                if (isAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
                
                var userList = context.Users.ToList();
                return View(userList);
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View();
        }

        [Authorize]
        public ActionResult Detail(string Id) {
            if (String.IsNullOrEmpty(Id)) {
                Id = User.Identity.GetUserId();
                ViewBag.isOwner = "true";
            }
            if (User.Identity.GetUserId() == Id) {
                ViewBag.isOwner = "true";
            }
            var user = (context).Users.Where(u => u.Id == Id).FirstOrDefault();
            var userInfo = DAL.DBContext.GetUserInfo(Id);
            var lstFavor = db.tb_Favorite.Where(f => f.UserId == userInfo.Id).ToList();
            var lstGroup = db.tb_UserGroup.Where(g => g.MemberId == userInfo.Id).ToList();

            ViewData["Groups"] = lstGroup;

            ViewData["Favorite"] = lstFavor;
            return View(user);
        }

        [Authorize]
        public ActionResult Edit(string Id) {
            var user = (context).Users.Where(u => u.Id == Id).FirstOrDefault();
            string roleId = user.Roles.Where(r => r.UserId == user.Id).FirstOrDefault().RoleId;
            string role = context.Roles.Where(r => r.Id == roleId).FirstOrDefault().Name;
            ViewBag.CurrentRole = role;
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(ApplicationUser user, string role)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            var oldUser = context.Users.Where(u => u.Id == user.Id).FirstOrDefault();
            //Delete current User
            var result = context.Users.Remove(oldUser);
            context.SaveChanges();
            //Add Edited User
            context.Users.Add(user);
            context.SaveChanges();
            //Add role to Edited User
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            UserManager.AddToRole(user.Id, role);
            return RedirectToAction("Index");

        }

    }
}

Views/Users/Detail.cshtml
@model SocialMedia.Models.ApplicationUser
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h5>@(new SocialMedia.Models.ApplicationDbContext().Users.Where(u => u.Id == Model.Id).FirstOrDefault().UserName)</h5>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            Role
        </dt>

        <dd>
            @{
                var roleId = Model.Roles.Where(r => r.UserId == Model.Id).FirstOrDefault().RoleId;
                var role = (new SocialMedia.Models.ApplicationDbContext()).Roles
                    .Where(r => r.Id == roleId)
                    .FirstOrDefault().Name;
            }
            @Html.DisplayFor(model => role)
        </dd>

        @if (ViewBag.isOwner != null)
        {
            <dt>
                Change Password
            </dt>

            <dd>
                @if (Model.PasswordHash != null)
                {
                    @Html.ActionLink("[Change]", "ChangePassword", "Manage")
                }
                else
                {
                    @Html.ActionLink("[Create]", "SetPassword", "Manage")
                }

            </dd>
        }
    </dl>
</div>

<hr/>
<div>
    <h4>Blog Favorite:</h4>
    <table class="table">
        <tr>
            <th>Title</th>
            <th></th>
        </tr>
        @foreach (var item in (List<tb_Favorite>)ViewData["Favorite"])
        {
    <tr>
        <td>@item.tb_Blog.Title</td>
        @if (ViewBag.isOwner != null)
        {
            <td>@Html.ActionLink("Unlike", "UnLike", "Blog", new { id = item.BlogId, returnUrl = Request.Url.AbsolutePath }, null)</td>

        }
    </tr>
        }
    </table>

    
</div>

<hr/>
<div>
    <h4>Blog Favorite:</h4>
    <table class="table">
        <tr>
            <th>Title</th>
            <th></th>
        </tr>
        @foreach (var item in (List<tb_UserGroup>)ViewData["Groups"])
        {
            <tr>
                <td>@item.tb_Group.Title</td>
                <td>@Html.ActionLink("Leave Group", "DeleteMember","Group", new { id = item.GroupId, memberId = User.Identity.GetUserId(), returnUrl = Request.Url.AbsolutePath }, null)</td>

            </tr>
        }
    </table>


</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Users/Edit.cshtml
@model SocialMedia.Models.ApplicationUser


@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Edit</h2>

 
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ApplicationUser</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.EmailConfirmed)
                @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumberConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.PhoneNumberConfirmed)
                @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.TwoFactorEnabled)
                @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.LockoutEnabled)
                @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AccessFailedCount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("role", new SelectList(new SocialMedia.Models.ApplicationDbContext().Roles.ToList(), "Name","Name",ViewBag.CurrentRole),"Role", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Users/Index.cshtml
@model IEnumerable<SocialMedia.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<string> roleList = ViewBag.RoleList;
}

<h2>Index</h2>

@{
    ViewBag.Title = "Index";
}

@if (User.Identity.IsAuthenticated)
{
    <h1>Welcome Admin. Now you can create user Role.</h1>
    <h3>
        <li>@Html.ActionLink("Manage Role", "Index", "Role")</li>
    </h3>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayName("Role")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @{ 
                        var roleId = item.Roles.Where(r => r.UserId == item.Id).FirstOrDefault().RoleId;
                        var role = (new SocialMedia.Models.ApplicationDbContext()).Roles
                            .Where(r => r.Id == roleId)
                            .FirstOrDefault().Name;
                    }
                    @Html.DisplayFor(modelItem => role)
                </td>
                <td>
                    @item.Id |
                    @Html.ActionLink("Detail","Detail","Users", new { Id = item.Id}, null)
                </td>
            </tr>
        }

    </table>
}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) .We will add user module soon </h2>
}